#!/usr/bin/env python3
"""Generate Tessera's synthetic ethical-wall data (Phase 4, plan §3.5.2).

Deterministic: a fixed seed plus sorted iteration over the restricted
engagement summaries in ``data/corpus/`` and the expertise dataset in
``data/expertise/people/``, so re-running produces byte-identical YAML.
Committed alongside its output (``data/access/walls.yaml``); a test fails
if the two drift.

Run from the repo root:  ``python data/access/generate.py``

The model (Discovery §4): Meridian's ethical walls are per-engagement lists
of named people cleared for that engagement. Everyone not on a list is
walled from it. Each engagement is staffed from people whose project
history covers the engagement's lead topic — a pyramid of one partner,
one principal, one engagement manager, two consultants and two analysts —
so the cleared lists look like real teams. Three demo personas are picked
from the result: a cleared partner, a walled analyst in the same practice,
and someone cleared for a different engagement only.

Like the corpus and the expertise data, all of this is fictional.
"""

from __future__ import annotations

import random
from pathlib import Path

import frontmatter
import yaml

SEED = 20261003

REPO_ROOT = Path(__file__).resolve().parents[2]
CORPUS_DIR = REPO_ROOT / "data" / "corpus"
PEOPLE_DIR = REPO_ROOT / "data" / "expertise" / "people"
OUT_FILE = Path(__file__).resolve().parent / "walls.yaml"

# Team shape per engagement: (title, how many).
TEAM_SHAPE: list[tuple[str, int]] = [
    ("Partner", 1),
    ("Principal", 1),
    ("Engagement Manager", 1),
    ("Consultant", 2),
    ("Analyst", 2),
]

# The engagement the demo personas are built around: a pricing
# engagement, so a walled pricing analyst has an obvious reason to ask.
PERSONA_ENGAGEMENT = "halcyon"
CROSS_CLEARED_ENGAGEMENT = "kestrel"

HEADER = """\
# Generated by data/access/generate.py — do not edit by hand.
#
# Ethical walls: engagement codename -> person_ids cleared for it. Anyone
# not listed is walled from that engagement (deny by default). The people
# are from data/expertise/people/; the engagements are the restricted
# summaries under data/corpus/engagements/. Fictional, like both.
#
# personas: named people with known clearances, for the demo and the
# access eval sets (evals/cases/access_*.yaml). These are DEMO
# identities — Tessera has no authentication.
"""


def load_engagements() -> list[tuple[str, list[str]]]:
    """(codename, topics) for every restricted document, sorted."""
    found: dict[str, list[str]] = {}
    for md in sorted(CORPUS_DIR.rglob("*.md")):
        post = frontmatter.load(md)
        if post.get("sensitivity") == "restricted":
            found[post["engagement"]] = list(post.get("topics") or [])
    return sorted(found.items())


def load_people() -> list[dict]:
    people: list[dict] = []
    for path in sorted(PEOPLE_DIR.glob("*.yaml")):
        people.extend(yaml.safe_load(path.read_text(encoding="utf-8")))
    return sorted(people, key=lambda p: p["person_id"])


def staff(rng: random.Random, topics: list[str], people: list[dict]) -> list[str]:
    """One team for an engagement: for each title, people whose project
    history covers the lead topic first, then any of its other topics,
    then anyone with that title.
    """
    lead, others = topics[0], set(topics[1:])
    team: list[str] = []
    for title, count in TEAM_SHAPE:
        with_title = [p for p in people if p["title"] == title]
        tiers = [
            [p for p in with_title if any(h["topic"] == lead for h in p["project_history"])],
            [p for p in with_title if any(h["topic"] in others for h in p["project_history"])],
            with_title,
        ]
        chosen: list[str] = []
        for tier in tiers:
            pool = [p["person_id"] for p in tier if p["person_id"] not in chosen]
            rng.shuffle(pool)
            chosen.extend(pool[: count - len(chosen)])
            if len(chosen) == count:
                break
        team.extend(chosen)
    return sorted(team)


def pick_personas(
    rng: random.Random, walls: dict[str, list[str]], people: list[dict]
) -> dict[str, dict[str, str]]:
    by_id = {p["person_id"]: p for p in people}
    cleared_anywhere = {pid for team in walls.values() for pid in team}
    target = walls[PERSONA_ENGAGEMENT]

    partner = next(pid for pid in target if by_id[pid]["title"] == "Partner")
    practice = by_id[partner]["practice"]
    walled = sorted(
        p["person_id"]
        for p in people
        if p["title"] == "Analyst"
        and p["practice"] == practice
        and p["person_id"] not in cleared_anywhere
    )
    cross = sorted(
        pid
        for pid in walls[CROSS_CLEARED_ENGAGEMENT]
        if pid not in target
        and sum(pid in team for team in walls.values()) == 1
    )
    return {
        "cleared_partner": {
            "person_id": partner,
            "note": f"cleared for {PERSONA_ENGAGEMENT}",
        },
        "walled_analyst": {
            "person_id": rng.choice(walled),
            "note": f"same practice as {PERSONA_ENGAGEMENT}'s team, cleared for nothing",
        },
        "cross_cleared": {
            "person_id": rng.choice(cross),
            "note": f"cleared for {CROSS_CLEARED_ENGAGEMENT} only, walled from {PERSONA_ENGAGEMENT}",
        },
    }


def build() -> dict:
    rng = random.Random(SEED)
    people = load_people()
    walls = {code: staff(rng, topics, people) for code, topics in load_engagements()}
    return {"walls": walls, "personas": pick_personas(rng, walls, people)}


def render(data: dict) -> str:
    return HEADER + yaml.safe_dump(data, sort_keys=False, allow_unicode=True)


def main() -> None:
    OUT_FILE.write_text(render(build()), encoding="utf-8")


if __name__ == "__main__":
    main()
